id: PCCC15881
initial_creation_type: input
source_metadata:
  title: Fire Offering Series
  language: en
  description: 'Texts related to the ritual of fire offering (homa; sbyin sreg/me
    mchod):'
  volume:
    20b00af19f574ec6bd9b4be5c27e86fc:
      title: 'Jewels of Many Colours: Ordinary Fire Pūjas for the Four Activities
        Based on a Single Substance to Easily Conclude Approach and Accomplishment'
      parent: Practices
    df79a0b5e3e94c64a59ce268eb7aa9fe:
      title: 'The Treasury of the Four Activities: A Fire Offering to Yumka'
      parent: Practices
    3b054741d0d34bf68b00773a3f0d6052:
      title: 'Bestowing the Splendour of All That is Desirable: Fire Offering for
        the ''Neck-Pouch Dagger’ (Purba Gulkhukma) Cycle'
      parent: Practices
    2e807ae595cf422987677d3abdbbb062:
      title: 'Bright Light of the Sun: A Simple Fire Offering Based on a Single Substance'
      parent: Practices
created_at: '2022-03-01T03:41:22.825773'
last_modified_at: '2022-03-01T03:41:22.825779'
